# Use this config file as a template for creating model runs
# Naming convention should follow this: modellingscenariodescription_modelbeingused, e.g. baseline_deterministic

# specify the input population parameter location
population_parameters:

# specify the model parameter location
model_parameters:

# specify the model that is being chosen
model_choice: 

# specify the intervention strategy
intervention_strategy: null 

# specify the output folder
output_location: null



